language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - php: 7.0

sudo: false

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS plftest;' -uroot;

script:
    -phpunit -d date.timezone=UTC tests/travis/phpunit_mysql.xml --coverage-text